 /******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Mohamed Ragab
 ******************************************************************************/

#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Dio_PBcfg.c and Dio.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Dio_PBcfg.c and Dio.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif

/* PB structure used with Port_Init API */
const Port_ConfigType Port_Configuration = {
                PORTA , PIN0, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTA , PIN1, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTA , PIN2, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTA , PIN3, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTA , PIN4, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTA , PIN5, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTA , PIN6, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTA , PIN7, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,

		PORTB , PIN0, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTB , PIN1, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTB , PIN2, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTB , PIN3, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTB , PIN4, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTB , PIN5, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTB , PIN6, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTB , PIN7, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,

		PORTC , PIN0, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTC , PIN1, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTC , PIN2, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTC , PIN3, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTC , PIN4, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTC , PIN5, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTC , PIN6, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTC , PIN7, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,

		PORTD , PIN0, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTD , PIN1, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTD , PIN2, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTD , PIN3, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTD , PIN4, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTD , PIN5, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTD , PIN6, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTD , PIN7, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,

		PORTE , PIN0, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTE , PIN1, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTE , PIN2, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTE , PIN3, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTE , PIN4, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTE , PIN5, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,

		PORTF , PIN0, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTF, PIN1, GPIO_MODE , OUTPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTF, PIN2, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTF, PIN3, GPIO_MODE , INPUT , OFF, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON,
		PORTF, PIN4, GPIO_MODE , INPUT , PULL_UP, PORT_PIN_LEVEL_LOW , STD_ON, STD_ON
                                           };